name = "contact-remarketing-bot"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
output_directory = "dist"

[env.production]
NODE_VERSION = "20"

[site]
bucket = "./dist"

[ssl]
enforce_https = true
minimum_tls_version = "1.2"
strict_transport_security = true

[site.static]
spa = true
error_page = "/index.html"

[pages]
pages_build_output_dir = "dist" 